Skip white space only text part. (#346)
When the planner delegates to sub agent, sometimes it returns text
response with pure space.
Fix the error:

```
ax exec --input "Use the hello-world agent to greet me."
Conversation: 8bbf7b84-f15d-480d-916d-ed8b9318f631

⏺ Use the hello-world agent to greet me.

Hello World



seq=3

⏺ who are you

Error: error executing with local server: failed to generate in planner: Error 400, Message: * GenerateContentRequest.contents[2].parts[0].data: required oneof field 'data' must have one initialized field
, Status: INVALID_ARGUMENT, Details: [map[@type:type.googleapis.com/google.rpc.DebugInfo detail:[ORIGINAL ERROR] generic::invalid_argument: * GenerateContentRequest.contents[2].parts[0].data: required oneof field 'data' must have one initialized field
 [google.rpc.error_details_ext] { message: "* GenerateContentRequest.contents[2].parts[0].data: required oneof field \'data\' must have one initialized field\n" details { type_url: "type.googleapis.com/language_labs.genai.debug.GeminiApiDebugInfo" value: "\242\001\250\001\np* GenerateContentRequest.contents[2].parts[0].data: required oneof field \'data\' must have one initialized field\n\0224net/proto2/contrib/validator/validator_util.cc:117:0" } }]]
```